- Message.hpp
피그마에따르면  private 변수는 _(언더바)를 하기로 했기에 진행
> [Refactor] Message 클래스 private 변수명 언더바 추가 close #3

- Channel.hpp
- Server.hpp
- commands/Part.hpp
기본 클래스 오류 수정
- Channel에 setName 제거
- Part에 execute() 리턴값 추가
- Server에 adminName 제거
> [Fix] 기본 클래스 오류 수정

- Server.hpp
[Fix] Server 의 channel 과 user를 static 으로 변경
- Server 의 channel 과 user를 static 으로 변경
- Command 에서 불러올때 Channel 과 User조회시 서버를 생성할 필요없이 호출해서 사용하기 위함
> [Fix] Server 의 channel 과 user를 static 으로 변경

- User.hpp
[Fix] User에 fd 추가
Message 를 넘겨줄때 User 의 fd 값을 가져가서 write을 해주기 용이하게 할것!
> [Fix] User에 fd 추가 Close #12

- commands/Command.hpp
Command class에 User 추가
Command class에 User 추가 ( 누가 명령어를 실행했는지 알아야 내부에서 처리할 수 있음 )
> [Fix] Command 객체에 User client 추가 close #15

- Message.hpp
Message Class 생성자 변경 
- `Message(std::vector<int> targets, int code, std::string prefix, std::string command, std::string params = "")`로 생성자 변경
> [Fix] Message Class 생성자 변경 close #11

- User.hpp
[Fix] AddUserGetter Close 
게터추가요 ㅠㅠ 힘드네용
- 내용을 적어주세요.
> [Fix] AddUserGetter Close #18

- Message.hpp
- User.hpp
- commands/Command.hpp
- srcs/socket.cpp
서버 소켓 생성 및 기본 설정
- 소켓 생성
- 주소 및 포트 할당
- 연결 요청 대기
- 소켓 플래그 설정 (non-block)
> [Feat] server socket

- commands/Msg.cpp
- commands/Msg.hpp
- commands/Privmsg.cpp
- commands/Privmsg.hpp
Msg command 생성자 변경, 이름 수정
- Msg command 생성자 변경 #22 
- Msg class 클래스명 수정 #27
> [Feat/Refactor] msg command close #27

- User.hpp
- commands/Command.hpp
- commands/Kick.cpp
- commands/Kick.hpp
- commands/List.cpp
- commands/List.hpp
- commands/Msg.cpp
- commands/Msg.hpp
- commands/Oper.cpp
- commands/Oper.hpp
- commands/Privmsg.cpp
- commands/Privmsg.hpp
Command class 자식들 구현, 명세에 맞게 수정
- #25
> [Fix] command child classes close #25

- Channel.hpp
- Server.hpp
- User.hpp
- commands/Command.hpp
- commands/Kick.cpp
- commands/Kick.hpp
- commands/List.cpp
- commands/List.hpp
- commands/Msg.cpp
- commands/Msg.hpp
- commands/Oper.cpp
- commands/Oper.hpp
- commands/Privmsg.cpp
- commands/Privmsg.hpp
Server class, Channel class 함수들 일부 구현
- #23
> [Feat] Server and channel #23

- commands/Kick.cpp
- commands/Oper.cpp
- commands/Privmsg.cpp
인자 빼먹은거 추가
- findChannel(), findUser() 인자로 User client 추가
> [Fix] find~class에 client 인자로 넘겨주도록 수정 #25

- .gitignore
- srcs/utils.cpp
- srcs/utils.hpp
split 함수 구현
파싱에 사용되는 split 함수를 구현했습니다.
> [Feat] split 함수 구현 #32

- srcs/utils.cpp
- srcs/utils.hpp
utils에 get_code_message() 추가
- #35
> [Feat] error message 반환함수 추가 close #35

- srcs/socket.cpp
서버 소켓에 이벤트 핸들러를 추가하여 클라이언트 접속 확인하고 클라이언트 소켓 생성
- 서버 소켓에 read에 대한 이벤트 추가
- 클라이언트 접속(서버 소켓에 발생하는 이벤트)에 대한 동작 추가
- 클라이언트 접속 확인
- 클라이언트 접속 시도 시 accept하여 연결
- 이벤트 등록용 kevent와 발생한 이벤트를 불러올 kevent 분리
- 이벤트 등록용 kevent 배열은 vector 구조체로 변경
> 37 feat 서버 소켓에 이벤트 핸들러 추가

- commands/Command.cpp
- commands/Command.hpp
Command 클래스 구현
- 내용을 적어주세요.
- 내용을 적어주세요.
> [Feat] Command 클래스 구현 Close #41

- .gitignore
- client_test.cpp
> 44 test 클라이언트 연결 확인 테스트

- commands/Join.cpp
- commands/Join.hpp
join을 Convention 에 맞게 맞추었습니다 
테스트도 하고 푸쉬합니다 믿고 사용해주세요
> [Feat] Join 클래스 구현 #49

- Server.cpp
- Server.hpp
client 데이터 불일치 문제 해결(서버 <-> 채널)
- addClientToChannel() 추가
- removeClientFromChannel() 추가
- #58
> [Fix] {add/remove}Client{To/From}Server close #58

- Client.cpp
- Client.hpp
- commands/PrivMsg.cpp
client class에 hostName 추가
- client class에 hostName 추가
- hostName getter, setter 추가
- PrivMsg prefix에 hostName 추가
> [Feat] client class에 hostName 추가 #24

- commands/User.cpp
- commands/User.hpp
user command 구현
- user command 구현
- #51
> [Feat] user command close #51

- Channel.cpp
- Channel.hpp
- Client.hpp
- Makefile
- Message.cpp
- Message.hpp
- Server.cpp
- Server.hpp
- commands/Command.hpp
- commands/Join.cpp
- commands/Kick.cpp
- commands/List.cpp
- commands/Oper.cpp
- commands/PrivMsg.cpp
- commands/User.cpp
- commands/User.hpp
- testCommand.cpp
Message class 너무 복잡시러워서 바꿈
- 생성자 수정 (코드 있는거 / 없는거)
- 거기에 따른 커맨드들 다 변경
> [Fix] Message class constructor changed close #65

- Channel.cpp
- Makefile
- Message.cpp
- commands/Join.cpp
- commands/Part.cpp
- commands/Part.hpp
- commands/Quit.cpp
- commands/Quit.hpp
- testCommand.cpp
Part 구현과 Quit 수정 chennel removeClient추가
- #69
> [Feat] Part 구현과 quit 수정 chennel removeClient추가 #69

- .gitignore
- Makefile
- srcs/client_socket.hpp
- srcs/main.cpp
- srcs/main.hpp
- srcs/server_socket.cpp
- srcs/server_socket.hpp
- srcs/validate_args.cpp
- srcs/validate_args.hpp
실행파일에 (port, password) 2개의 인자를 받게끔 설정하고, 서버 클래스 객체를 생성해서 저장
- 실행파일은 (port, password) 2개의 argument를 받음
- port는 숫자인지, 포트 번호 범위인지 유효성 검사
- password는 화이트스페이스로만 채워져 있는 유효성 검사
- 서버 클래스 객체 생성 및 인자 넣어 초기화
- 헤더 가드 언더스코어 삭제함 (아깐 진짜 참조가 안됐어..)
- Makefile 추가/수정 했습니다
> [Feat] 실행파일 args 핸들링 server 객체 생성 #62

- Client.cpp
- Client.hpp
- Server.cpp
- Server.hpp
- srcs/client_socket.cpp
- srcs/client_socket.hpp
- srcs/main.cpp
- srcs/utils.cpp
- srcs/utils.hpp
- srcs/validate_args.cpp
- srcs/validate_args.hpp
클라이언트 호스트 따려고 작업 시작했지만 우선 컴파일 에러 먼저 수정해야 함
- 컴파일 플래그 에러 수정
- 이것 저것..
> [Feat] user class에 host 주소 추가 #24

- Channel.cpp
- Makefile
- Server.cpp
- commands/Kick.cpp
- commands/List.cpp
- commands/Part.cpp
- srcs/utils.hpp
- testCommand.cpp
Kick command test
- Kick command test
- removeClientFromChannel 에서 client 수 체크하도록 변경
> [Test] Kick command #60

- Channel.hpp
- Client.cpp
- Client.hpp
- Server.cpp
- commands/Join.cpp
- srcs/utils.cpp
client에 channel추가
- client가 속해있는 channel을 모아둔 map 멤버 변수를 추가했습니다.
- 해당 map에서 channel을 추가/제거할 수 있는 멤버 함수를 추가했습니다.
- 내용을 적어주세요.
> [Feat] client에 channel추가 Close #77

- Channel.cpp
- Client.cpp
- Client.hpp
- Server.cpp
- testCommand.cpp
client, channel 상호 참조로 인한 컴파일 오류 해결
- client가 channel 목록을 set으로 가지고 있도록 수정
- 해당 내용에 맞춰서 함수들 수정
> [Fix] 컴파일 오류 해결 close #82

- Client.cpp
- Makefile
- Message.cpp
- Message.hpp
- Server.cpp
- Server.hpp
- commands/Command.hpp
- commands/Oper.cpp
- commands/Oper.hpp
- commands/Part.cpp
- commands/Part.hpp
- commands/Pass.cpp
- commands/Pass.hpp
- commands/PrivMsg.cpp
- commands/PrivMsg.hpp
- commands/Quit.cpp
- commands/Quit.hpp
- commands/User.cpp
- commands/User.hpp
- srcs/client_socket.cpp
- srcs/main.cpp
- srcs/parse.cpp
- srcs/parse.hpp
- srcs/utils.cpp
- srcs/utils.hpp
Pass 클래스 구현 및 파싱 함수 적용
- 클라이언트 최초 접속 시 확인하는 패스워드를 위한 Pass 클래스 구현
- Message 객체에서 targets를 불러오는 getter 추가
- Server 클래스를 static으로 수정
- main 함수에 클라이언트로 부터 받은 메시지를 파싱하여 타겟에게 `send()` 해주는 부분 추가
- 내용을 적어주세요.
> [Feat] Pass 클래스 구현 및 파싱 함수 적용 #87 #89

- Client.cpp
- Client.hpp
- Message.cpp
- Server.cpp
- Server.hpp
- commands/Join.cpp
- commands/Kick.cpp
- commands/List.cpp
- commands/Nick.cpp
- commands/Oper.cpp
- commands/Part.cpp
- commands/Pass.cpp
- commands/PrivMsg.cpp
- commands/Quit.cpp
- srcs/client_socket.cpp
- srcs/client_socket.hpp
- srcs/main.cpp
> [Fix] Server에 있는 static 함수 수정 Close #101

- srcs/main.cpp
- srcs/utils.cpp
- srcs/utils.hpp
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> [Fix] 닫힌 소켓에 대한 조건 추가

- Message.cpp
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
> [Feat] 뭔가빠졌네요..

- Channel.cpp
- Client.cpp
- Makefile
- commands/Nick.cpp
- srcs/main.cpp
abort 해결, nick 메시지 중복 해결
- abort 해결
- nick 메시지 중복되는 문제 해결
> [Fix] abort 해결, nick 메시지 중복 해결 close #108

- Channel.cpp
- Server.cpp
- Server.hpp
- commands/Join.cpp
bot 명령어 설계및 추가
Server에 bot을 Client 로 생성해서  join시 PrivMsg로 출력해용
그래서 우리 봇은 입장에 맞춰서 방장임을 알려준답니다!
> [Feat] bot추가 Close #115

- srcs/command/Join.cpp
- srcs/command/Join.hpp
- srcs/message/Message.cpp
- srcs/message/Message.hpp
join시 현재 채널에 있는 유저목록 반환 
- join시 현재 채널에 있는 유저목록 반환
> [Feat] join시 유저목록 반환 close #98

- srcs/client_socket.cpp
- srcs/command/Join.cpp
- srcs/command/Kick.hpp
- srcs/command/Nick.cpp
- srcs/command/Part.cpp
- srcs/command/PrivMsg.cpp
- srcs/command/Quit.cpp
- srcs/ircserv.hpp
- srcs/main.cpp
- srcs/message/Message.cpp
- srcs/parse.cpp
- srcs/server/Server.cpp
- srcs/server/Server.hpp
- srcs/utils.cpp
- srcs/utils.hpp
출력문 정리 및 server.execute() 추가
- main문의 while문을 Server 객체의 execute 함수로 분리했습니다.
- 출력문 삭제했습니다.
- 닉네임을 소문자로만 처리하도록 수정했습니다.
> [Refactor] 출력문 정리 및 server.execute() 추가 #116

- srcs/client_socket.cpp
에러시 fd close() 처리
- kevent() 실패 시 fd close 후 fail return
> [Fix] 에러시 fd close() 처리 close #116

- srcs/client/Client.cpp
- srcs/client/Client.hpp
- srcs/command/Command.hpp
- srcs/command/Nick.cpp
- srcs/server/Server.cpp
마지막 테스트하며 코드 리팩토링
- 유저 닉네임 중복 조건 수정 #127 
- 필요없는 조건문 삭제
- 더이상 사용하지 않는 프로퍼티/함수들 삭제
- 평가에 필요한 주석 내 변수명 수정
- 딱히 없음
> [Fix] 마지막테스트

- srcs/command/Join.cpp
- srcs/command/PrivMsg.cpp
> [Fix] join, privmsg # 처리 close #132

- srcs/command/User.cpp
- srcs/parse.cpp
setter execute 할때 진행 
USER 명령어에서 username setting 합니당
parse에서 4개쪼개다가 3개쪼개는걸로 바꿨어요
> [Fix] user setting possible Close - 135

- srcs/command/Command.cpp
- srcs/command/Command.hpp
- srcs/command/Join.cpp
- srcs/command/Join.hpp
- srcs/command/Kick.cpp
- srcs/command/Kick.hpp
- srcs/command/List.cpp
- srcs/command/List.hpp
- srcs/command/Nick.cpp
- srcs/command/Nick.hpp
- srcs/command/Oper.cpp
- srcs/command/Oper.hpp
- srcs/command/Part.cpp
- srcs/command/Part.hpp
- srcs/command/Pass.cpp
- srcs/command/Pass.hpp
- srcs/command/Ping.cpp
- srcs/command/Ping.hpp
- srcs/command/PrivMsg.cpp
- srcs/command/PrivMsg.hpp
- srcs/command/Quit.cpp
- srcs/command/Quit.hpp
- srcs/command/User.cpp
- srcs/command/User.hpp
- srcs/message/Message.cpp
- srcs/message/Message.hpp
- srcs/server/Server.cpp
에러 처리합니다.
- command class에 validate()함수 추가
- 각각 execute() 앞에 validate() 실행
- ^D 입력시 계속 입력 받도록 하는 로직 추가
- 
- 내용을 적어주세요.
> [Fix] error handling #130

- srcs/command/Join.cpp
- srcs/command/Join.hpp
- srcs/command/Quit.cpp
- srcs/server/Server.cpp
fsanitize=address 옵션 넣었을때 에러 터지는 부분 수정
- Quit()에서 fd 닫아버리면 터지는 부분 발견 -> 수정
- Nick()으로 닉네임 변경시 이미 찾은 client 사용하면 터지는 부분 수정
- 디버깅 메시지 삭제
- Join()에서 이미 접속중인 채널에 다시 요청 보냈을 때 에러 메시지 -> continue로 그냥 넘기도록 수정
- nc로 여러 번 join시 다른 접속중인 client들에게 bot message가 날아가는 문제가 있었음..
> [Fix] 마지막 수정
